### ISSUE TITLE
pyautogui does not support UTF-8 typewrite

### ISSUE THREAD

**Issue by RiMikheev** [IntegraSDL/pygats#28]
pyautogui does not support UTF-8 typewrite

**Comment by vsysoev** [comment]
https://pypi.org/project/keyboard/

**Comment by RiMikheev** [comment]
The following script is used to write text in Russian:
```
import pyautogui, pyperclip

def paste(text: str):    
    buffer = pyperclip.paste()
    pyperclip.copy(text)
    pyautogui.hotkey('ctrl', 'v')
    pyperclip.copy(buffer)
```
Article: https://ru.stackoverflow.com/questions/1139110/%D0%9F%D0%B5%D1%87%D0%B0%D1%82%D1%8C-%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%B8%D1%85-%D1%81%D0%B8%D0%BC%D0%B2%D0%BE%D0%BB%D0%BE%D0%B2-%D0%B2-pyautogui
You also need to install one of the copy/paste mechanisms:
```

    sudo apt-get install xsel to install the xsel utility.
    sudo apt-get install xclip to install the xclip utility.
    pip install gtk to install the gtk Python module.
    pip install PyQt4 to install the PyQt4 Python module.
```
Source: https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error

**Comment by vsysoev** [comment]
Looks like hack )

**Comment by vsysoev** [comment]
Pull request #31 implements workaround of this issue
